name: frontend
channels:
  - defaults
dependencies:
  - pandas
  - transformers
  - streamlit
  - matplotlib
  - pytorch
  - sentencepiece
  - plotly
  - scipy
  - nltk
  - spacy
prefix: /opt/anaconda3/envs/frotend-env
